### PR TITLE
Add two Irelands

### PR DESCRIPTION
**Pull request by hugovk**
- [National Library of Ireland on The Commons](data/47290943@N03) – _last archived 20131224_
- [Public Record Office of Northern Ireland](data/54403180@N04) – _last archived 20131224_

### CODE REVIEW

**Comment by hugovk** [comment]
This branch should now have all the remaining institutions (apart from BL/SDASM/MDAH which @straup has in process) and is ready for merge.

**Comment by straup** [comment]
I tried to add your changes but there seem to be a number of outstanding conflicts, mostly with

http://www.flickr.com/photos/109550159@N08

Can you (re) sync all your stuff with master and let me know. I'll hold off on making any changes on my side, until then.

Cheers,

**Comment by hugovk** [comment]
Will do.

**Comment by straup** [comment]
Did this happen yet? It's not urgent or anything. I'm just trying to keep track of who's on first (and make sure that people aren't waiting on me :-)

**Comment by hugovk** [comment]
It's in progress, I'll continue on Monday.

Just for info, this is what I did. First updated your master (upstream) to my branch, then merged. Of course, both operations took a long time with such big lumps of data. And of course, the automatic merge left loads of "<<<<<<< HEAD" things in each file and there's no point inspecting each by hand.

So, take 2 was to grab both my branch (big wait...) and the upstream (big wait...), then do a big diff with Beyond Compare (less big wait...), then for each institution directory, check one or two files to see which side was updated most recently, then keep that one (bit smaller wait...). This is much easier, as there's not so many dirs with diffs. I'll then diff the README by hand.

**Comment by straup** [comment]
Cool, thanks.

The big waiting is not ideal. I'm not sure what to do about that yet. Ed Summers has suggested git-annex which might be a good solution but I'd like to grab at least one complete (-ish) copy of all the metadata before going down that avenue.

**Comment by hugovk** [comment]
Update: still in progress.

I pushed a first partial-merge to my branch. After the remaining merge, the `git add` took 60 hours, `git commit` took 27 hours, and `git push` took 68 hours before I killed it when it appeared to have stalled at the "Counting objects: 4xxxxxx, done" stage (didn't note the exact number, but was over 4 million!).

To do:
After I've pushed this merge to my branch for safe-keeping, do a `git pull` from your branch, then a `git merge` should go smoothly. Then that can be pushed back.

**Comment by straup** [comment]
Glurgh. There's a how-to / how-to-not do things in all of this...

**Comment by hugovk** [comment]
Now sitting at:
"Counting objects: 4653674, done."

git.exe using about 3% CPU and 708,000 K memory.

**Comment by straup** [comment]
It might be worth running `make prune` to pack the .git bits, if you haven't already. It takes a while.

**Comment by hugovk** [comment]
Update:

"... then a `git merge` should go smoothly." I said, optimistically.

So... 

I did the merge locally and have pushed it all up to https://github.com/hugovk/flickr-commons-metadata/tree/irelands for safe keeping.

The `git merge` from upstream/master didn't go smoothly, twice.

I'd been keeping the most recent files from each side. As a last attempt I've made a new branch from a fresh clone of upstream/master, then _only_ adding those missing institutions. I'm more optimistic because when I'd been working on a single branch only adding fresh files from the script, it was slow-ish (hours, not thousands of hours). Hopefully merging with just new files, and none changed, will be better.

I have been doing the prune from time to time. It does indeed take a while. Just for fun, here's some of the timings from the failed attempts, that once included a corrupt index. The repo is about 8GB on disk:
- add 60 hours
- commit 27h
- push 68h
- push 61h
- fetch upstream 83h
- prune 5h
- merge upstream 3h
- reset 15h

**Comment by hugovk** [comment]
So I'll close this PR and make a new one with the new branch. I'll leave the old branches up as a backup.

**Pull request closed without merging**
