### PR TITLE
Added metadata from The Society of Swedish Literature in Finland

### PR DESCRIPTION
**Pull request by hugovk**
SLS is a Flickr Commons member.

### CODE REVIEW

**Comment by hugovk** [comment]
Oh, looks like you have added this already! That'll teach me not to commit before going out for the day...

**Comment by straup** [comment]
Heh, yeah. Not sure how to coordinate these sorts of things. I'm just picking institutions at random. Maybe I will add an "in-process" section.

**Comment by straup** [comment]
https://github.com/straup/flickr-commons-metadata/commit/d8c12d09ceebfe232a62ab4afc095b0b74271334

I'll look at your changes later tonight.

**Comment by straup** [comment]
Added at some point in the slipstream.

**Pull request closed without merging**
